template_path: locust/cluster.yaml

stack_tags:
  ProjectCode: {{ project_code }}
  Documentation: "https://github.com/lvdh/distributed-locustio-on-aws/"

parameters:
  InstanceCount: !environment_variable CLUSTER_INSTANCE_COUNT
  InstanceTypes: !environment_variable CLUSTER_INSTANCE_TYPES
  EC2KeyName: !environment_variable CLUSTER_EC2_KEY_NAME

  SolutionStackName: "64bit Amazon Linux 2018.03 v2.14.1 running Go 1.13.2"
  VPCID: !stack_output locust/network.yaml::VPCID
  VPCCIDR: !stack_output locust/network.yaml::VPCCIDR
  PrivateSubnets: !stack_output locust/network.yaml::PrivateSubnets
  PublicSubnets: !stack_output locust/network.yaml::PublicSubnets
