template_path: locust/cluster.yaml

stack_tags:
  ProjectCode: {{ project_code }}
  Documentation: "https://github.com/lvdh/distributed-locustio-on-aws/"

parameters:
  InstanceCount: !environment_variable CLUSTER_INSTANCE_COUNT
  InstanceTypes: !environment_variable CLUSTER_INSTANCE_TYPES
  EC2KeyName: !environment_variable CLUSTER_EC2_KEY_NAME

  ElasticBeanstalkPlatform: "64bit Amazon Linux 2018.03 v2.14.1 running Go 1.13.2"
  VpcId: !stack_output locust/network.yaml::VpcId
  VpcCidrBlock: !stack_output locust/network.yaml::VpcCidrBlock
  PrivateSubnetIds: !stack_output locust/network.yaml::PrivateSubnetIds
  PublicSubnetIds: !stack_output locust/network.yaml::PublicSubnetIds
