template_path: locust/cluster.yaml

stack_tags:
  ProjectCode: {{ project_code }}
  Documentation: https://github.com/lvdh/distributed-locustio-on-aws/blob/master/README.md

parameters:
  ClusterInstanceCount: "3"
  SSHKeyPairName: "kp-laurens"
  VPCID: !stack_output locust/network.yaml::VPCID
  VPCCIDR: !stack_output locust/network.yaml::VPCCIDR
  PrivateSubnets: !stack_output locust/network.yaml::PrivateSubnets
  PublicSubnets: !stack_output locust/network.yaml::PublicSubnets
